databases:
  - name: postgres
    ipAllowList: []
    databaseName: my_app_render
    user: my_app_render

services:
  - type: web
    name: my_app_render
    env: ruby
    buildCommand: ".bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: postgresql://essohbasecamp_user:MghzkIftjHOYO10HnjcK4B8wWpKaWK9P@dpg-cqcg0rg8fa8c73cpebc0-a/essohbasecamp
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false