databases:
  - name: postgres
    ipAllowList: []
    databaseName: my_app_render
    user: my_app_render

services:
  - type: web
    name: my_app_render
    env: ruby
    buildCommand: ".bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: postgresql:DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
